# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [3]:
print(np.__version__)

1.16.2


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
x=np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)

In [7]:
x.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000022ACCA20A20>, toplevel='numpy')>

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
y=np.zeros(10)

In [11]:
y[4]=10

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
y=np.arange(10,50)

In [16]:
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [17]:
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
y=np.arange(0,9)

In [19]:
y.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [21]:
l=np.nonzero([1,2,0,0,4,0])

In [22]:
print(l)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
l=np.eye(3)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [29]:
p=np.random.random((3,3,3))
print(p)

[[[0.28575269 0.10811656 0.10231824]
  [0.80547428 0.4536719  0.81868128]
  [0.510225   0.41050725 0.3617688 ]]

 [[0.09913655 0.30129721 0.54732002]
  [0.41118897 0.49273548 0.0624444 ]
  [0.47796215 0.1469553  0.82268905]]

 [[0.42882761 0.40111132 0.57150913]
  [0.75201286 0.91387019 0.05229549]
  [0.21810303 0.01919075 0.87870537]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
p=np.random.random((10,10))
maxnumber, minnumber=p.max(), p.min()
print(maxnumber, minnumber)

0.9862363104985016 0.003013110398874641


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
p=np.random.random(30)
x=p.mean()
print(x)

0.5317903912928631


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
p= np.ones((10,10))
p[1:-1,1:-1] = 0
print(p)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [33]:
p= np.ones((5,5))
p= np.pad(p, pad_width=1, mode='constant', constant_values=0)
print(p)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [35]:
p= np.diag(1+np.arange(4),k=-1)
print(p)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [36]:
p= np.zeros((8,8),dtype=int)
p[1::2,::2] = 1
p[::2,1::2] = 1
print(p)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [37]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [38]:
a= np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [39]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.94309736  0.91999477 -0.00522725 -0.58321791  0.16587207]
 [-1.43089776 -0.0263533  -1.54520046 -0.32354755  1.53311135]
 [ 1.2477654   1.36309766  0.14084891 -0.70477931  1.31735941]
 [ 1.62021167 -1.31476919  0.75634093 -0.76101554 -0.40858403]
 [ 0.96502436 -1.48725032 -0.7930196  -0.50345319  0.80078624]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [40]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
a= np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [42]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:

2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [47]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [48]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-3.  6. -4. -7.  4.  7.  2. 10.  9.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [5]:
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [53]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2019-10-12 2019-10-13 2019-10-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [54]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [55]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [57]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[7. 7. 9. 2. 3. 3. 1. 9. 9. 9.]
[7. 7. 9. 2. 3. 3. 1. 9. 9. 9.]
[7. 7. 9. 2. 3. 3. 1. 9. 9. 9.]
[7 7 9 2 3 3 1 9 9 9]
[7. 7. 9. 2. 3. 3. 1. 9. 9. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [58]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [7]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [59]:
Z = np.linspace(0,1,11)[1:]
print(Z)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [60]:
p=np.random.random(10)
p.sort()
print(p)

[0.03018026 0.09021751 0.12994394 0.13369285 0.14121449 0.22778446
 0.3416394  0.39274903 0.45906465 0.56448222]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [61]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [62]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [8]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [64]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.04142831 0.96280125 1.06925863 0.84198857 1.01947283 0.34654305
 0.83626956 0.43989366 0.72370858 0.5453455 ]
[0.52454474 0.93219223 1.03122855 1.03118162 0.58990826 0.84032095
 0.66952134 1.08732165 0.16577632 1.51461653]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [65]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.47885591 0.12669406 0.         0.83677328 0.2623359  0.29368924
 0.5160123  0.05930746 0.06084816 0.87506782]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [9]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [11]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [12]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [66]:
ar=np.random.random(50)
print(ar)

[0.89649834 0.74307736 0.37327093 0.79825038 0.6543558  0.18982637
 0.13459193 0.11455785 0.29742801 0.12824317 0.43993928 0.88324906
 0.38279509 0.61611479 0.4656275  0.13004365 0.24165149 0.10875495
 0.28349841 0.0560687  0.77572098 0.69211765 0.42908226 0.68672309
 0.09279254 0.64791478 0.95073818 0.4422024  0.24677411 0.32097902
 0.10468822 0.29913303 0.19673278 0.48283407 0.80441944 0.78840292
 0.40582243 0.5719491  0.18832254 0.89410131 0.58474117 0.86997851
 0.06253226 0.06094345 0.9686097  0.0158146  0.66946944 0.98296473
 0.5879537  0.14187789]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [67]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

46


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [13]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [14]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.41784287 0.39630922 0.25591822 0.41856218 0.65966679
  0.12035704 0.46023428 0.46438404 0.58791175]
 [0.41784287 0.         0.60048036 0.51645935 0.09572702 0.41410639
  0.48328455 0.38853341 0.13951111 0.20191834]
 [0.39630922 0.60048036 0.         0.64872534 0.53415181 0.55907771
  0.50308493 0.317858   0.54330028 0.66414334]
 [0.25591822 0.51645935 0.64872534 0.         0.56126128 0.85866835
  0.14753248 0.69288515 0.61568043 0.71616393]
 [0.41856218 0.09572702 0.53415181 0.56126128 0.         0.32659096
  0.50360959 0.29674894 0.0553138  0.16941298]
 [0.65966679 0.41410639 0.55907771 0.85866835 0.32659096 0.
  0.76933039 0.24538734 0.27517104 0.27625341]
 [0.12035704 0.48328455 0.50308493 0.14753248 0.50360959 0.76933039
  0.         0.57867376 0.55405144 0.67001031]
 [0.46023428 0.38853341 0.317858   0.69288515 0.29674894 0.24538734
  0.57867376 0.         0.27869753 0.3751786 ]
 [0.46438404 0.13951111 0.54330028 0.61568043 0.0553138  0.27517104
  0.55405144 0.27869

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [15]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [16]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [17]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [18]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [19]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [21]:
X=np.random.rand(5,10)
y=X-X.mean(axis=1).reshape(-1,1)
print(y)

[[-0.01608245 -0.08001827 -0.30959345  0.43175488  0.37181952 -0.44540884
  -0.42866742  0.33441678 -0.34415944  0.48593868]
 [ 0.02719003  0.36867795 -0.07545611 -0.2954848   0.42310936 -0.1748344
  -0.34988496 -0.04666075 -0.3849338   0.50827748]
 [ 0.15995781  0.0357575   0.09492047 -0.35609745  0.34288935  0.31558053
  -0.32324142 -0.39877907  0.02898547  0.1000268 ]
 [ 0.05445526 -0.16268182  0.35589277 -0.23434665  0.51625546 -0.34587525
  -0.1671985   0.06399745 -0.2168833   0.13638458]
 [ 0.2044008  -0.42387169 -0.07509083 -0.36324831  0.09283891  0.42175269
   0.28548477 -0.0283459   0.0661014  -0.18002184]]


#### 59. How to sort an array by the nth column? (★★☆)

In [68]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 9 5]
 [6 2 5]
 [2 2 2]]
[[6 2 5]
 [2 2 2]
 [7 9 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [23]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())
print(Z)

False
[[1 2 1 2 1 2 2 2 0 0]
 [0 2 2 2 0 1 2 0 0 2]
 [0 0 2 0 0 0 2 0 2 2]]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [24]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5481539908936048


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [25]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [26]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [27]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[4. 4. 1. 3. 2. 1. 2. 5. 6. 2.]
[ 7.  7.  1.  5.  3.  1.  3.  9. 11.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [28]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [29]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [30]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 57 38 64]
 [53 56 53 52]
 [50 77 57 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [31]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.3989896  0.51895368 0.57956562 0.53663182 0.52258375 0.52352363
 0.65772086 0.37005203 0.45935219 0.34088486]


#### 69. How to get the diagonal of a dot product? (★★★)

In [32]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.84092744, 1.09449095, 1.80651872, 1.37021584, 1.11687788])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [33]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [34]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [69]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [35]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 35) ( 0, 77) ( 1, 52) ( 1, 68) ( 3, 59) ( 3, 87) ( 5,  7) ( 5, 91)
 ( 6, 62) ( 6, 63) ( 7, 32) ( 7, 91) ( 7, 95) (17, 87) (17, 98) (28, 74)
 (28, 95) (32, 95) (35, 77) (42, 55) (42, 61) (52, 68) (55, 61) (57, 85)
 (57, 99) (59, 87) (62, 63) (74, 95) (85, 99) (87, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [36]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [37]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [38]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [39]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.31355347,  0.67972187,  0.13362152, -0.95113231,  0.87012704,
        0.02080121,  0.7254925 ,  0.48660925, -0.36409893,  0.07720059,
       -0.93531216, -0.74420692, -0.22177928,  0.26057052,  0.61383549,
       -0.86274834,  0.33210005,  0.62835278, -0.11391356,  0.50362483,
       -0.69439185,  0.76940929, -0.09089945, -0.95164373, -0.31713499,
        0.54260426,  0.26646981,  0.327084  , -0.44436238, -0.46392306,
        0.05762935, -0.75581028,  0.14385471,  0.52575896,  0.63927059,
       -0.31583136,  0.67820442, -0.5792491 , -0.90085788, -0.97664402,
        0.28942989,  0.62452594, -0.64911604,  0.97709586, -0.61233501,
       -0.66683178,  0.9838225 ,  0.82039955,  0.37450529, -0.17764697,
        0.35324834, -0.49463615, -0.54109163,  0.42577727,  0.73615531,
       -0.93077058, -0.9425784 ,  0.29700724, -0.82537267,  0.56521097,
       -0.74361694, -0.32219921,  0.42808068, -0.31743345,  0.81202921,
        0.02079828,  0.57937717,  0.92173287, -0.92827449,  0.66

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [40]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.96910916  5.01961127  1.25043585  1.78914076  0.57786076 12.5679468
  1.78507618  7.42731404  7.42641669  1.9862317 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [41]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.41157725  4.08493372  6.13520078  5.1480847   1.08468232  1.94959274
  11.77869232 14.70936638  3.54884067  4.45167497]
 [ 0.8361172   4.98352051 14.38311547  0.42751964  6.3665958   3.1203668
   0.93560974  1.82598599  9.81089252  8.5158475 ]
 [ 7.04406746  4.94967119  0.25302281  4.27552934  7.90143298  7.45118462
   5.12505007  8.20906738  5.51824557  3.76934233]
 [ 5.40670419  0.8731807  11.96514587  4.22278305  3.69982267  7.78254965
   4.82086598  1.99937476  9.75943408  4.98393442]
 [ 5.20813316 10.2077684  17.02916417  6.65556335  9.37597095  3.14225618
   4.75318434  7.44728515  9.13757784 12.82272944]
 [12.10123601 10.35519707  5.16625629  9.10288975 12.95077264 12.21512984
   3.06122323  6.25903521  8.58328719  9.15339581]
 [ 3.94895511  8.97733842 16.10717411  5.41078151  8.40134929  1.90295439
   3.9383416   6.65437656  8.77948987 11.68093783]
 [ 0.1257814   4.12902961 10.40500592  2.04381891  2.71991939  1.34806104
   4.36343044  7.20770607  3.79034422  6.299439  ]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [42]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 4 1 8 9 1 9 8 4 7]
 [5 5 7 4 5 9 2 2 5 9]
 [4 1 8 6 9 8 6 4 8 0]
 [9 3 5 6 7 2 4 9 9 7]
 [1 6 6 8 0 8 4 4 8 4]
 [6 1 8 3 5 3 7 5 1 7]
 [0 0 9 2 4 3 7 5 5 5]
 [7 8 8 4 3 7 5 6 2 8]
 [5 6 1 5 0 5 3 0 3 6]
 [0 1 7 8 2 8 2 3 1 6]]
[[0 0 0 0 0]
 [0 2 4 1 8]
 [0 5 5 7 4]
 [0 4 1 8 6]
 [0 9 3 5 6]]


C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [43]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [44]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [45]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [46]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 4]
   [4 0 0]
   [2 3 1]]

  [[2 4 0]
   [0 0 4]
   [3 1 1]]

  [[4 0 1]
   [0 4 3]
   [1 1 3]]

  [[0 1 3]
   [4 3 4]
   [1 3 3]]

  [[1 3 1]
   [3 4 4]
   [3 3 0]]

  [[3 1 4]
   [4 4 4]
   [3 0 4]]

  [[1 4 2]
   [4 4 4]
   [0 4 3]]

  [[4 2 4]
   [4 4 3]
   [4 3 3]]]


 [[[4 0 0]
   [2 3 1]
   [1 0 4]]

  [[0 0 4]
   [3 1 1]
   [0 4 3]]

  [[0 4 3]
   [1 1 3]
   [4 3 4]]

  [[4 3 4]
   [1 3 3]
   [3 4 1]]

  [[3 4 4]
   [3 3 0]
   [4 1 0]]

  [[4 4 4]
   [3 0 4]
   [1 0 3]]

  [[4 4 4]
   [0 4 3]
   [0 3 0]]

  [[4 4 3]
   [4 3 3]
   [3 0 0]]]


 [[[2 3 1]
   [1 0 4]
   [3 0 0]]

  [[3 1 1]
   [0 4 3]
   [0 0 3]]

  [[1 1 3]
   [4 3 4]
   [0 3 1]]

  [[1 3 3]
   [3 4 1]
   [3 1 2]]

  [[3 3 0]
   [4 1 0]
   [1 2 4]]

  [[3 0 4]
   [1 0 3]
   [2 4 2]]

  [[0 4 3]
   [0 3 0]
   [4 2 1]]

  [[4 3 3]
   [3 0 0]
   [2 1 4]]]


 [[[1 0 4]
   [3 0 0]
   [1 3 3]]

  [[0 4 3]
   [0 0 3]
   [3 3 1]]

  [[4 3 4]
   [0 3 1]
   [3 1 4]]

  [[3 4 1]
   [3 1 2]
   [1 4 1]]

  [[4 1 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [47]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  8 11 14 10]
 [ 8  4  1 14 13]
 [11  1  4 42 10]
 [14 14 42  3 12]
 [10 13 10 12  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [48]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [49]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [50]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [51]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9996 9999 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [52]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [53]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [55]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.86 s ± 41.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
345 ms ± 11.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
286 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [56]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [58]:
Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 2 2]
 [2 3 4]
 [2 0 2]
 [2 3 4]
 [4 2 3]
 [4 2 2]
 [3 0 1]
 [2 3 4]
 [2 1 0]
 [0 0 1]]
[[4 2 2]
 [2 3 4]
 [2 0 2]
 [2 3 4]
 [4 2 3]
 [4 2 2]
 [3 0 1]
 [2 3 4]
 [2 1 0]
 [0 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [59]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [60]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [61]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.06472128, 0.54253064, 0.01763645, 0.42285146, 0.49613738,
        0.25631456, 0.25211131, 0.40200531, 0.14533754, 0.44144876],
       [0.09918037, 0.83138639, 0.0270265 , 0.64798728, 0.7602923 ,
        0.39278231, 0.38634116, 0.61604217, 0.22271858, 0.67648621],
       [0.0712884 , 0.59758003, 0.01942598, 0.46575727, 0.54647935,
        0.28232224, 0.2776925 , 0.44279591, 0.16008462, 0.4862416 ],
       [0.01145047, 0.09598439, 0.00312024, 0.07481078, 0.0877765 ,
        0.04534711, 0.04460347, 0.07112268, 0.02571308, 0.07810101],
       [0.09791942, 0.82081641, 0.0266829 , 0.63974897, 0.75062619,
        0.3877886 , 0.38142934, 0.60821   , 0.21988701, 0.66788558],
       [0.0615423 , 0.51588264, 0.01677019, 0.40208186, 0.47176813,
        0.24372492, 0.23972812, 0.38225964, 0.13819886, 0.41976571],
       [0.00619154, 0.05190103, 0.00168719, 0.04045196, 0.04746283,
        0.02452026, 0.02411815, 0.03845772, 0.01390367, 0.04223106],
       [0.05467992, 0.45835821, 0.0149002

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [62]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [63]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [64]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.15160508  0.26408813]
